version: '3.3'
services:
  db:
    container_name: db
    build:
      context: ./deployment/mysql
#    ports:
 #     - "3306:3306"
    environment:
#      - MYSQL_HOST=${DB_HOST}
      - MYSQL_DATABASE=db
      - MYSQL_USER=toor
      - MYSQL_PASSWORD=toor
      - MYSQL_ROOT_PASSWORD=root
#    command:
 #     --default-authentication-plugin=mysql_native_password
    volumes:
      - ./persistent_data/mysql:/var/lib/mysql
    network_mode: "host"

  webservice:
    container_name: disk_service
    build: .
    restart: on-failure
    volumes:
      - "/root/ya_enrollment:/disk_service"
#    ports:
 #     - "80:80"
#    links:
 #     - mysql
  #  depends_on:
   #   - db
    network_mode: "host"         
