# Generated by Django 4.1.1 on 2022-09-14 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Element",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=200,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parentId",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Parent ID"
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("type", models.CharField(max_length=6, verbose_name="Element type")),
                (
                    "date",
                    models.CharField(
                        blank=True, max_length=26, verbose_name="Current date"
                    ),
                ),
                (
                    "size",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="File size"
                    ),
                ),
            ],
        ),
    ]
